install_data(
  'io.github._6E6B.marshal.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data(
  'io.github._6E6B.marshal.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)

install_data(
  'io.github._6E6B.marshal.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)
