install_data(
  'io.github.marshal.Marshal.desktop',
  install_dir: get_option('datadir') / 'applications',
)

install_data(
  'io.github.marshal.Marshal.metainfo.xml',
  install_dir: get_option('datadir') / 'metainfo',
)

install_data(
  'io.github.marshal.Marshal.svg',
  install_dir: get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'apps',
)
